# Build setup for Travis CI

language:
  - java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true

script:
  - ./gradlew clean build jfxNative checkBundle -info

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: ####
  file:
    - "gui/build/distributions/LiquEc-${TRAVIS_TAG}.zip"
    - "package/build/jfx/native/liquec-${TRAVIS_TAG}.deb"
  skip_cleanup: true
  on:
    tags: true
    repo: LiquEc/LiquEc

